# -*- coding: utf-8 -*-
"""load_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ot3-36M2QRdtBlcITI3reMi3aDhyQ5Dp
"""

from keras.preprocessing.image import ImageDataGenerator

def Chest_XRay(batch_size,image_size,data_dir):

    '''
    Dataset : https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia
    '''


    data_dir ='/content/chest_xray'
    image_size= 224
    batch_size_train = 4
    batch_size_test = 4
    train_datagen = ImageDataGenerator(rotation_range=40,
                                    width_shift_range=0.2,
                                    height_shift_range=0.2,
                                    shear_range=0.2,
                                    zoom_range=0.2,
                                    rescale=1.0/255,
                                    horizontal_flip=True,
                                    fill_mode='nearest')
    test_datagen = ImageDataGenerator(rescale=1.0/255)

    train_path = data_dir+'/train'
    test_path = data_dir+'/test'

    classes = ['NORMAL','PNEUMONIA']

    train_batches = train_datagen.flow_from_directory(train_path, target_size=(image_size,image_size),color_mode='rgb', classes=classes, batch_size=batch_size_train,class_mode='categorical')
    test_batches = test_datagen.flow_from_directory(test_path, target_size=(image_size,image_size),color_mode='rgb', classes=classes, batch_size=batch_size_test, class_mode='categorical')  

    return train_batches,test_batches
