# -*- coding: utf-8 -*-
"""Output_Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ot3-36M2QRdtBlcITI3reMi3aDhyQ5Dp
"""

import matplotlib.pyplot as plt

def  plot_loss_acc(history):
    loss = history.history['loss']
    val_loss = history.history['val_loss']
    epochs = range(len(loss))
    plt.plot(epochs, loss, 'bo')
    plt.plot(epochs, val_loss, 'g')
    plt.title('Training and validation loss')
    plt.legend(['train', 'val'], loc='upper right')
    filename= 'xcep_pneu_loss.png'
    plt.savefig(filename)
    plt.show()
    
    acc = history.history['accuracy']
    val_acc = history.history['val_accuracy']
    epochs = range(len(acc))
    plt.plot(epochs, acc, 'b')
    plt.plot(epochs, val_acc, 'g')
    plt.title('Training and validation accuracy')
    plt.legend(['train', 'val'], loc='lower right')
    filename= 'xcep_pneu_accuracy.png'
    plt.savefig(filename)
    plt.show()